// vtes-subs.js · TRK-2026-9910-B · #SUBSCRIPTIONS · sliced from VTES-LLM-LAUNCHER.html by the build (a test keeps them equal)
// Read from Gmail receipts 2026-09-30. Card = nickname + last 4 only.
(function () {
  var SUBS = [
    { n: 'SuperGrok (Grok xAI)', c: '#2e7d4f', w: 'KEEP', feeds: 'LLM-07 Grok · Grok Bots · Grok Automations', cost: '$30.00 / month', bill: 'Stripe “Grok xAI”, charged on the 17th, Visa-4981. Next: 2026-10-17 (plus state sales tax starting Oct 1).', note: 'Six receipts in a row (Apr 17 to Sep 17). xAI says Grok Bot is now included with SuperGrok (8/27). Your two Grok Automations (Daily Planner, Alec microfilm 30-day clock) email you from this account.' },
    { n: 'X Premium Plus', c: '#b3261e', w: 'DUPLICATE?', feeds: 'Grok access on X · the X account perks', cost: '$40.00 / month (you remembered $20: the latest receipt says $40)', bill: 'Stripe “X”, charged on the 11th, Visa-4981. Next: 2026-10-11.', note: 'Monthly receipts from Feb 11 to Sep 11. This is the only other Grok-related charge in your email. Grok itself is covered by SuperGrok, so this plan is the duplicate. Cancelling it also removes the other X Premium features (blue check, longer posts, analytics). Only you can cancel it.' },
    { n: 'SpaceXAI API (developer console)', c: '#6b6b66', w: 'NO COST', feeds: 'Any tool that calls Grok by key', cost: '$0.00 usage, July 2026 invoice', bill: 'Usage-only. Nothing recurring. Keys stay in the console (never written to any file here).', note: 'Nothing to cancel. If any PC script uses an xAI key, it is unaffected by the two plans above.' },
    { n: 'Google AI Plus (2 TB) via Google One', c: '#2e7d4f', w: 'ACTIVE', feeds: 'LLM-08 Gemini · Drive storage', cost: '$9.99 / month', bill: 'Google Play, charged on the 4th, Visa-4981. Introductory price ended Sep 4.', note: 'This is the Gemini subscription found in your email. It is Google AI Plus, not Google AI Pro.' },
    { n: 'Microsoft 365 (Business Standard, Office 365 E3, Power Automate Premium)', c: '#6b6b66', w: 'ACTIVE', feeds: 'LLM-10 Copilot (if included) · Outlook · OneDrive', cost: 'Amounts not read', bill: 'Renewals on the 10th (Business Standard, Power Automate Premium) and the 12th (Office 365 E3). E3 price drops Oct 12.', note: 'No charge named Copilot exists in your email. Whether your plans include the full Copilot is UNVERIFIED: open copilot.microsoft.com signed in and see which tier it shows.' },
    { n: 'Claude (Anthropic)', c: '#6b6b66', w: 'ACTIVE', feeds: 'LLM-01 to LLM-05', cost: 'Amounts not read', bill: '12 receipts between Jun 29 and Sep 17 (dates vary: plan renewals or extra-usage purchases).', note: 'Not opened: not part of this duplicate question.' },
    { n: 'ChatGPT (for Codex)', c: '#7a2e8e', w: 'UNVERIFIED', feeds: 'LLM-06 Codex', cost: 'Unknown', bill: 'No OpenAI or ChatGPT receipt found in Gmail in the last 120 days.', note: 'It may bill to another email or through Apple. Codex is installed and waiting for your sign-in, so the plan is unproven until you sign in.' }
  ];
  window.VTES_SUBS = SUBS;
})();
